[package]
name = "nestr"
version = "0.1.0"
description = "Assistant de planification quotidienne piloté par IA"
authors = ["Thibaut Monier"]
edition = "2021"

[lib]
name = "nestr_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-oauth = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[features]
custom-protocol = ["tauri/custom-protocol"]
